credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "exampleuser-creds-id"
          username: "exampleuser"
          password: "{AQAAABAAAAAQ1/JHKggxIlBcuVqegoa2AdyVaNvjWIFk430/vI4jEBM=}"
          description: "Sample credentials of exampleuser"
          scope: GLOBAL        
jobs:
  - script: >
      pipelineJob('example') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/jenkinsci/job-dsl-plugin.git')
                        }
                    }
                }
                scriptPath('Jenkinsfile')
            }
         }
      }
globalConfigFiles:
  configs:
    - custom:
        id: sample-custom-config
        name: SampleCustomConfig
        comment: dummy custom 1
        content: dummy content 1

    - json:
        id: sample-json-config
        name: SampleJsonConfig
        comment: sample json config
        content: |
          { "dummydata": {"dummyKey": "dummyValue"} }
      
