credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "exampleuser-creds-id"
          username: "exampleuser"
          password: "{AQAAABAAAAAQ1/JHKggxIlBcuVqegoa2AdyVaNvjWIFk430/vI4jEBM=}"
          description: "Sample credentials of exampleuser"
          scope: GLOBAL
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code-demo') {
          branchSources {
              git {
                  id = 'configuration-as-code-demo'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
