jobs:
  - script: >
      pipelineJob('Deploy_infra') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/service-deployment-starter-helm.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('Jenkinsfile_deploy_infra')
            }
         }
      }
      
      pipelineJob('Infra_package') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/service-deployment-starter-helm.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('Jenkinsfile_infra_package')
            }
         }
      }
      
      pipelineJob('Deploy_qa') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/jenkins-shared-library.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('deploy/Jenkinsfile_deploy_qa')
            }
         }
      }
      
      pipelineJob('Deploy_staging') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/jenkins-shared-library.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('deploy/Jenkinsfile_deploy_stage')
            }
         }
      }
      
      pipelineJob('Secrets scanner') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/service-starter.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('JenkinsfileSecrets')
            }
         }
      }
      
      pipelineJob('security') {
        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            url('https://github.com/twCatalyst/service-starter.git')
                            credentials('githubCredentials')

                        }
                    }
                }
                scriptPath('JenkinsfileSecurity')
            }
         }
      }
      
      organizationFolder('catalyst') {
          displayName('catalyst')
          triggers {
              periodic(1)
          }
          organizations {
              github {
                  repoOwner("twCatalyst")
                  apiUri("https://api.github.com")
                  credentialsId('githubCredentials')

              }
          }
          projectFactories {
              workflowMultiBranchProjectFactory {
                  scriptPath("Jenkinsfile")
              }
          }
      }
      
